### ISSUE TITLE
An exception was thrown during startup

### ISSUE THREAD

**Issue by Daocuong-main** [Natsu235/Gibbed.TinyTinaAoDK#2]
Laptop acer swift 3
OS: Windows 11

```
---------------------------
Error
---------------------------
An exception was thrown during startup (press Ctrl+C to copy):

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Windows.Markup.XamlParseException: 'Set property 'Caliburn.Micro.Message.Attach' threw an exception.' Line number '45' and line position '6'. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Windows.Interactivity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

   at Gibbed.TinyTinaAoDK.SaveEdit.AppBootstrapper.<>c__DisplayClass1_0.<Configure>b__0(DependencyObject target, String triggerText)

   at Caliburn.Micro.Parser.Parse(DependencyObject target, String text)

   at Caliburn.Micro.Message.OnAttachChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)

   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)

   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)

   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)

   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)

   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)

   at System.Windows.Baml2006.WpfMemberInvoker.SetValue(Object instance, Object value)

   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)

   --- End of inner exception stack trace ---

   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)

   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)

   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)

   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)

   at Gibbed.TinyTinaAoDK.SaveEdit.ShellView.InitializeComponent()

   at Gibbed.TinyTinaAoDK.SaveEdit.ShellView..ctor()

   --- End of inner exception stack trace ---

   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)

   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)

   at System.Activator.CreateInstance(Type type, Boolean nonPublic)

   at System.Activator.CreateInstance(Type type)

   at Caliburn.Micro.ViewLocator.<.cctor>b__2(Type viewType)

   at Caliburn.Micro.ViewLocator.<.cctor>b__e(Object model, DependencyObject displayLocation, Object context)

   at Caliburn.Micro.WindowManager.CreateWindow(Object rootModel, Boolean isDialog, Object context, IDictionary`2 settings)

   at Caliburn.Micro.WindowManager.ShowWindow(Object rootModel, Object context, IDictionary`2 settings)

   at Gibbed.TinyTinaAoDK.SaveEdit.AppBootstrapper.OnStartup(Object sender, StartupEventArgs e)
---------------------------
OK   
---------------------------

```

**Comment by meechew** [comment]
I found the same issue.

**Comment by meechew** [comment]
I used the standalone save editor and did not get this error.
